export const locations = [
  {
    id: '1',
    name: 'Central Library',
    description: 'A quiet place to study with lots of books.',
    address: 'Ludwigstraße 16, 80539 München',
    category: 'library',
    latitude: 48.137154,
    longitude: 11.576124,
    has_wifi: 1,
    has_outlets: 1,
    has_outside_seating: 0,
    has_beverages: 0,
    has_food: 0,
    inside_seats: 'Many',
    outside_seats: 'None',
    noise_level: 'quiet',
    hours: '9am-8pm',
    image_url: '',
    rating: 4.5,
    created_date: '2023-01-01T00:00:00.000Z'
  },
  {
    id: '2',
    name: 'Café Einstein',
    description: 'Cozy café with good coffee and wifi.',
    address: 'Einsteinstraße 42, 81675 München',
    category: 'cafe',
    latitude: 48.139126,
    longitude: 11.580186,
    has_wifi: 1,
    has_outlets: 1,
    has_outside_seating: 1,
    has_beverages: 1,
    has_food: 1,
    inside_seats: 'Few',
    outside_seats: 'Some',
    noise_level: 'moderate',
    hours: '7am-6pm',
    image_url: '',
    rating: 4.0,
    created_date: '2023-01-01T00:00:00.000Z'
  },
  {
    id: '3',
    name: 'TU München Campus',
    description: 'Technical University campus with study areas.',
    address: 'Arcisstraße 21, 80333 München',
    category: 'university',
    latitude: 48.1497,
    longitude: 11.5678,
    has_wifi: 1,
    has_outlets: 1,
    has_outside_seating: 1,
    has_beverages: 0,
    has_food: 0,
    inside_seats: 'Many',
    outside_seats: 'Some',
    noise_level: 'moderate',
    hours: '24/7',
    image_url: '',
    rating: 4.2,
    created_date: '2023-01-01T00:00:00.000Z'
  }
];